version: "3.9"
networks:
  robopapa:
    driver: bridge
services:
  web:
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on: 
    - catalogue
    - mongodb
  catalogue: 
     image: catalogue:v1 
     container_name: catalogue
     depends_on:
     - mongodb
  mongodb: 
    image: mongo:v1
    container_name: mongo

    